SET GDATASET_categorical(GDATASET)
/
GDTYPE                                    'Generation type'                                                                                                    
GDFUEL                                             
GDTECHGROUP                               'Technology group'                                                                                                   
GDSUBTECHGROUP                            'SubTechnology group'
/;